# Nombre del pipeline
# Esto es lo que vemos en la pestaña "Actio
name: CI Laravel


# Evento que dispara el pipeline
# Define CUÁNDO GitHub debe ejecutar est
on:
  push:
  pull_request:

# Aquí se definen los trabajos del pipeline
jobs:
  build-test:
    runs-on: ubuntu-latest

# Lista de pasos que se ejecutan en orden
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Instalar dependencias
        run: composer install --no-interaction --prefer-dist

      - name: Preparar entorno
        run: cp .env.example .env || true

      - name: Generar APP_KEY
        run: php artisan key:generate

      - name: Ejecutar pruebas
        run: php artisan test