# Nombre del pipeline
# Esto es lo que vemos en la pestaña "Actio
name: CI Laravel


# Evento que dispara el pipeline
# Define CUÁNDO GitHub debe ejecutar est
on:
  push:
  pull_request:

# Aquí se definen los trabajos del pipeline
jobs:
  build-test:
    runs-on: ubuntu-latest

# Lista de pasos que se ejecutan en orden
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Instalar dependencias
        run: composer install --no-interaction --prefer-dist

      - name: Preparar entorno
        run: cp .env.example .env || true

      - name: Generar APP_KEY
        run: php artisan key:generate

      - name: Ejecutar pruebas
        run: php artisan test
      
      - name: Enviar correo - Pipeline OK
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ✅ Pipeline CI PASÓ
          to: ${{ secrets.EMAIL_TO }}
          from: "CI Laravel <${{ secrets.EMAIL_USERNAME }}>"
          body: |
            El pipeline CI se ejecutó correctamente.
            
            ✅ Build exitoso
            ✅ Pruebas pasaron
            
            Commit: ${{ github.sha }}
            Repositorio: ${{ github.repository }}

            
      - name: Enviar correo - Pipeline FALLÓ
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ❌ Pipeline CI FALLÓ
          to: ${{ secrets.EMAIL_TO }}
          from: "CI Laravel <${{ secrets.EMAIL_USERNAME }}>"
          body: |
            ❌ El pipeline CI falló.
            
            Revisar el error en GitHub Actions.
            
            Commit: ${{ github.sha }}
            Repositorio: ${{ github.repository }}

        
      - name: Deploy a PRODUCCION 
        if: success()
        run: |
          echo "🚀 Desplegando a producción"
          echo "Commit desplegado: ${{ github.sha }}"
          echo "Repositorio: ${{ github.repository }}"
          echo "Fecha: $(date)"


